#!/usr/bin/env bash
# ===================================================================
# 新しいマシンでこの設定を動かすための初期化スクリプト
#
#   git clone <repo> ~/.config/nvim-viewer
#   ~/.config/nvim-viewer/scripts/bootstrap.sh
#
# 既存の nvim があるかどうかに関わらず、この形で入れる。
# ~/.config/nvim には触れないので、既存の設定は壊れず、
# 無い場合もそこを空けたままにできる（後で普通の nvim を使いたくなったとき）。
# 起動は nvim-viewer（このスクリプトが用意する）。
#
# 方針:
#   - sudo を使わない（mise / npm / go install で完結させる）
#   - 何度実行しても壊れない（入っているものは飛ばす）
#   - 勝手に消さない・上書きしない
#   - 何をしたか最後にまとめて出す
# ===================================================================
set -uo pipefail

# pwd -P で実体のパスにそろえる。
# ~/.config/nvim を symlink にして実体を別の場所に置く構成
# （個人アカウント用のディレクトリ配下に置きたい場合など）でも
# 同じ場所だと判定できるようにするため。
NVIM_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
# XDG_DATA_HOME を尊重する（Lua 側の md_preview.lua と同じ場所を指すこと）
LIB_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/nvim-md-preview"
PUPPETEER_JSON="$NVIM_DIR/mermaid-puppeteer.json"

# この設定の名前。nvim は $XDG_CONFIG_HOME/$NVIM_APPNAME を設定として読む。
#
# **既定は nvim ではなく nvim-viewer。** 配布物なのだから名前は自分で名乗る。
# 置き場所から推測すると、clone 先を変えただけで別人になってしまう。
# ~/.config/nvim を占有しないので、普通の nvim と共存できる。
#
# 意図して別名にしたい場合だけ NVIM_APPNAME で上書きできる。
DEFAULT_APPNAME="nvim-viewer"
APPNAME="${NVIM_APPNAME:-$DEFAULT_APPNAME}"
XDG_CFG="${XDG_CONFIG_HOME:-$HOME/.config}"
export NVIM_APPNAME="$APPNAME"   # 以降で呼ぶ nvim にも引き継ぐ
# 起動コマンドの名前は導入先によらず常に同じにする。
# 配布したときに「どちらで入れたか」を聞かないと
# 起動方法を案内できない、という状態を避けるため。
LAUNCHER="$HOME/.local/bin/nvim-viewer"
LAUNCHER_MARK="# generated by nvim viewer bootstrap"

DONE=(); SKIP=(); WARN=()
ok()   { DONE+=("$1"); printf '  \033[32m✓\033[0m %s\n' "$1"; }
skip() { SKIP+=("$1"); printf '  \033[90m-\033[0m %s（導入済み）\n' "$1"; }
warn() { WARN+=("$1"); printf '  \033[33m!\033[0m %s\n' "$1"; }
head_() { printf '\n\033[1m%s\033[0m\n' "$1"; }

has() { command -v "$1" >/dev/null 2>&1; }

# -------------------------------------------------------------------
head_ "0. 置き場所の確認"
# -------------------------------------------------------------------
# nvim は $XDG_CONFIG_HOME/$NVIM_APPNAME しか見ない。
# 別の場所に clone した状態で実行すると、プラグインやパーサーの導入だけが
# 「本物の設定」に対して行われ、意図しない結果になる。
EXPECTED="${XDG_CONFIG_HOME:-$HOME/.config}/$APPNAME"
if [ "$NVIM_DIR" != "$(cd "$EXPECTED" 2>/dev/null && pwd -P || echo "")" ]; then
  printf '  \033[33m!\033[0m このリポジトリは %s にあります\n' "$NVIM_DIR"
  printf '    このスクリプトは %s 用と判断しました（読む場所は %s）。\n' "$APPNAME" "$EXPECTED"
  printf '    そこへ clone し直すか、symlink を張ってから実行してください。\n\n'
  printf '    推奨の入れ方（既存の nvim の有無に関わらず同じ）:\n'
  printf '      git clone <repo> ~/.config/nvim-viewer\n'
  printf '      ~/.config/nvim-viewer/scripts/bootstrap.sh\n\n'
  printf '    中断しました。\n'
  exit 1
fi
if [ "$NVIM_DIR" != "$EXPECTED" ]; then
  ok "配置は正しい（$EXPECTED → $NVIM_DIR / NVIM_APPNAME=$APPNAME）"
else
  ok "配置は正しい（$NVIM_DIR / NVIM_APPNAME=$APPNAME）"
fi

# 既存の nvim 設定を壊していないかを、はっきり示す
ok "~/.config/nvim には触れません（普通の nvim と共存します）"

# -------------------------------------------------------------------
head_ "1. 前提ツールの確認"
# -------------------------------------------------------------------
for c in git curl; do
  has "$c" && skip "$c" || warn "$c が無い。先に入れてください"
done
# git が無いとプラグインもパーサーも取得できない。
# 続けても「導入できた」と嘘の報告をするだけなので、ここで止める。
if ! has git; then
  printf '\n  git が無いため続行できません（プラグインの取得に必要です）。\n'
  printf '  中断しました。\n\n'
  exit 1
fi

if ! has mise; then
  warn "mise が無い。https://mise.jdx.dev/ を見て入れるか、neovim を自分で用意してください"
fi

# -------------------------------------------------------------------
head_ "2. Neovim（0.11 以上が必要）"
# -------------------------------------------------------------------
need_nvim=1
if has nvim; then
  ver=$(nvim --version | head -1 | grep -oE '[0-9]+\.[0-9]+' | head -1)
  major=${ver%%.*}; minor=${ver##*.}
  if [ "$major" -gt 0 ] || [ "$minor" -ge 11 ]; then
    skip "neovim $ver"; need_nvim=0
  else
    warn "neovim $ver は古い（0.11 以上が必要）。入れ直します"
  fi
fi
if [ "$need_nvim" = 1 ] && has mise; then
  mise use -g neovim@latest >/dev/null 2>&1 && ok "neovim を導入" || warn "neovim の導入に失敗"
fi

# -------------------------------------------------------------------
head_ "3. tree-sitter CLI（パーサーのビルドに必須）"
# -------------------------------------------------------------------
if has tree-sitter; then
  skip "tree-sitter"
elif has npm; then
  npm install -g tree-sitter-cli >/dev/null 2>&1 \
    && { has mise && mise reshim >/dev/null 2>&1; ok "tree-sitter-cli を導入"; } \
    || warn "tree-sitter-cli の導入に失敗"
else
  warn "npm が無いため tree-sitter-cli を入れられない（パーサーがビルドできません）"
fi

# -------------------------------------------------------------------
head_ "4. 言語サーバ（プロジェクトの言語に応じて）"
# -------------------------------------------------------------------
if has npm; then
  if has vtsls; then skip "vtsls (TypeScript)"
  else
    npm install -g @vtsls/language-server typescript >/dev/null 2>&1 \
      && ok "vtsls / typescript を導入" || warn "vtsls の導入に失敗"
  fi
  if has vscode-json-language-server; then skip "vscode-langservers-extracted"
  else
    npm install -g vscode-langservers-extracted >/dev/null 2>&1 \
      && ok "vscode-langservers-extracted を導入" || warn "同上の導入に失敗"
  fi
  has mise && mise reshim >/dev/null 2>&1
fi

if has go; then
  if has gopls; then skip "gopls (Go)"
  else
    go install golang.org/x/tools/gopls@latest >/dev/null 2>&1 \
      && { has mise && mise reshim >/dev/null 2>&1; ok "gopls を導入"; } || warn "gopls の導入に失敗"
  fi
else
  skip "gopls（go が無いので飛ばす）"
fi

# Kotlin は Java が要り重いので、既に java がある場合だけ案内する
if has java && ! has kotlin-language-server; then
  warn "Kotlin を使うなら kotlin-language-server の導入が別途必要（docs/design-notes.md 第4.3節）"
fi

# -------------------------------------------------------------------
head_ "5. マークダウンのブラウザ表示用"
# -------------------------------------------------------------------
if has npm; then
  if has mmdc && has marked; then
    skip "mermaid-cli / marked"
  else
    PUPPETEER_SKIP_DOWNLOAD=1 npm install -g @mermaid-js/mermaid-cli marked >/dev/null 2>&1 \
      && { has mise && mise reshim >/dev/null 2>&1; ok "mermaid-cli / marked を導入"; } \
      || warn "mermaid-cli / marked の導入に失敗"
  fi

  # ブラウザ描画用のライブラリを、node のバージョンに依存しない場所へ複製する。
  #
  # 置き場所を決め打ちにしてはいけない。npm はバージョンによって依存を
  # 巻き上げたり巻き上げなかったりする。実際 mermaid は
  #   <root>/mermaid/dist/…                              （巻き上げられた場合）
  #   <root>/@mermaid-js/mermaid-cli/node_modules/mermaid/dist/… （されない場合）
  # の両方があり、直下だけを見ていると**永久に複製できず**、
  # 「入れ直してください」と案内しても直らない状態になる。
  mkdir -p "$LIB_DIR"
  NM="$(npm root -g 2>/dev/null)"
  for pair in "mermaid/dist/mermaid.min.js:mermaid.min.js" "marked/lib/marked.umd.js:marked.umd.js"; do
    rel="${pair%%:*}"; dst="$LIB_DIR/${pair##*:}"
    src="$(find "$NM" -maxdepth 6 -path "*/$rel" -print -quit 2>/dev/null)"
    [ -n "$src" ] && cp "$src" "$dst"
  done
  # 判定は「コピーした本数」ではなく「使える状態か」で行う。
  # 既に置いてあって機能している場合に失敗と報告しないため。
  if [ -s "$LIB_DIR/mermaid.min.js" ] && [ -s "$LIB_DIR/marked.umd.js" ]; then
    ok "描画ライブラリを $LIB_DIR に用意"
  else
    warn "描画ライブラリが見つかりません。Space o（ブラウザ表示）が動きません"
  fi
fi

# -------------------------------------------------------------------
head_ "6. Chrome のパス設定（mermaid を図にするため）"
# -------------------------------------------------------------------
CHROME=""
for c in google-chrome google-chrome-stable chromium chromium-browser microsoft-edge brave-browser; do
  if has "$c"; then CHROME="$(command -v "$c")"; break; fi
done
if [ -n "$CHROME" ]; then
  # --no-sandbox は付けない。
  # このビューアーは「素性の知れないリポジトリを安全に読む」ための道具で、
  # mermaid の描画には信頼できない入力がそのまま渡る。そこで Chrome の
  # プロセスサンドボックスを切るのは、道具の目的と正面から矛盾する。
  # コンテナなど user namespace が使えない環境で描画に失敗する場合だけ、
  # 利用者が自分の判断で args に "--no-sandbox" を足すこと。
  cat > "$PUPPETEER_JSON" <<JSON
{
  "executablePath": "$CHROME",
  "args": ["--disable-dev-shm-usage"]
}
JSON
  ok "mermaid-puppeteer.json を生成（$CHROME）"
else
  warn "ブラウザが見つからない。mermaid の画像変換は使えません（HTMLプレビューは動きます）"
fi

# -------------------------------------------------------------------
head_ "7. プラグインとパーサーの導入"
# -------------------------------------------------------------------
if has nvim; then
  # ★ sync ではなく restore を使う。
  #   sync  = 最新に更新する（lazy-lock.json の固定を無視して書き換えてしまう）
  #   restore = lazy-lock.json のコミット通りに入れる
  # 「どのマシンでも同じ版が入る」「勝手に更新されない」という利点は
  # restore を使って初めて成立する。
  nvim --headless "+Lazy! install" +qa >/dev/null 2>&1
  nvim --headless "+Lazy! restore" +qa >/dev/null 2>&1
  # 終了コードは当てにならない（init.lua が落ちても 0 を返す）。
  # 実際に入った数を数えて判定する。
  pn=$(nvim --headless -c 'lua
local ok, cfg = pcall(require, "lazy.core.config")
io.stderr:write(("\nVIEWER_PLUGINS=%d\n"):format(ok and vim.tbl_count(cfg.plugins) or 0))
vim.cmd("qa!")' 2>&1 | grep -o 'VIEWER_PLUGINS=[0-9]*' | tail -1 | cut -d= -f2)
  if [ "${pn:-0}" -ge 8 ]; then
    ok "プラグイン $pn 個をロック通りに導入"
  else
    warn "プラグインの導入に失敗（$pn 個しか読み込めていません）"
  fi

  echo "  パーサーを導入中（数分かかります）..."
  # 一覧は lua/core/parsers.lua が持つ。ここに書き写すとズレるので読む。
  nvim --headless -c 'lua
local ok, ts = pcall(require, "nvim-treesitter")
if not ok then vim.cmd("qa!") end
local ok2, want = pcall(require, "core.parsers")
if not ok2 then vim.cmd("qa!") end
local h = ts.install(want)
if h and h.wait then h:wait(900000) end
vim.cmd("qa!")' >/dev/null 2>&1
  # 件数は目印付きで出して grep で拾う。
  # nvim-treesitter は導入の進捗を非同期で stderr に流すので、
  # `tail -1` では**その進捗行を掴んでしまい**、初回だけ判定が壊れる。
  counts=$(nvim --headless -c 'lua
local okt, ts = pcall(require, "nvim-treesitter")
local okl, want = pcall(require, "core.parsers")
local have = {}
if okt then for _, x in ipairs(ts.get_installed()) do have[x] = true end end
local miss = 0
if okl then for _, x in ipairs(want) do if not have[x] then miss = miss + 1 end end end
io.stderr:write(("\nVIEWER_PARSERS=%d VIEWER_WANT=%d VIEWER_MISSING=%d\n"):format(
  okt and #ts.get_installed() or 0, okl and #want or 0, miss))
vim.cmd("qa!")' 2>&1 | grep -o 'VIEWER_PARSERS=[0-9]* VIEWER_WANT=[0-9]* VIEWER_MISSING=[0-9]*' | tail -1)
  n=$(echo "$counts"    | grep -o 'VIEWER_PARSERS=[0-9]*'  | cut -d= -f2)
  want_n=$(echo "$counts" | grep -o 'VIEWER_WANT=[0-9]*'   | cut -d= -f2)
  miss=$(echo "$counts"   | grep -o 'VIEWER_MISSING=[0-9]*' | cut -d= -f2)
  if [ "${miss:-1}" = "0" ] && [ "${want_n:-0}" != "0" ]; then
    ok "パーサー $want_n 件を導入（導入済み合計 $n 件）"
  else
    warn "パーサーが揃っていません（不足 ${miss:-?} 件 / 想定 ${want_n:-?} 件）"
  fi
fi

# -------------------------------------------------------------------
head_ "8. 起動用コマンド"
# -------------------------------------------------------------------
# 毎回 NVIM_APPNAME を打つのは現実的でないので、短いラッパーを用意する。
if [ -e "$LAUNCHER" ] && ! grep -q "$LAUNCHER_MARK" "$LAUNCHER" 2>/dev/null; then
  # 自分が作ったものでなければ絶対に触らない
  warn "$LAUNCHER が既にあります（別のもののようなので上書きしません）"
else
  mkdir -p "$(dirname "$LAUNCHER")"
  cat > "$LAUNCHER" <<LAUNCH
#!/usr/bin/env bash
$LAUNCHER_MARK
# 既存の nvim 設定に触れずに、閲覧専用ビューアーを起動する
exec env NVIM_APPNAME="$APPNAME" nvim "\$@"
LAUNCH
  chmod +x "$LAUNCHER"
  ok "起動コマンドを作成: $LAUNCHER"
  case ":$PATH:" in
    *":$(dirname "$LAUNCHER"):"*) : ;;
    *) warn "$(dirname "$LAUNCHER") が PATH にありません。シェルの設定に追加してください" ;;
  esac
fi

# -------------------------------------------------------------------
head_ "9. 動作確認"
# -------------------------------------------------------------------
if has nvim; then
  # LSP の確認は実際のソースファイルで行う（空バッファでは起動しない）
  probe=$(git -C "$NVIM_DIR" ls-files '*.lua' 2>/dev/null | head -1)
  probe="${probe:+$NVIM_DIR/$probe}"
  result=$(nvim --headless ${probe:+"$probe"} -c 'lua vim.wait(2500)' -c 'lua
local n = 0
for l in vim.fn.execute("messages"):gmatch("[^\n]+") do
  if l:match("^E%d+:") then n = n + 1 end
end
io.stderr:write("errors=" .. n .. " lsp=" .. table.concat(vim.g.viewer_lsp_enabled or {}, ","))
vim.cmd("qa!")' 2>&1 | tail -1)
  case "$result" in
    errors=0*) ok "起動エラーなし（${result#errors=0 }）" ;;
    *) warn "起動時にエラーがあります: $result" ;;
  esac
fi

# -------------------------------------------------------------------
head_ "結果"
# -------------------------------------------------------------------
printf '  導入 %d件 / 既存 %d件 / 要確認 %d件\n' "${#DONE[@]}" "${#SKIP[@]}" "${#WARN[@]}"
if [ "${#WARN[@]}" -gt 0 ]; then
  printf '\n  \033[33m要確認:\033[0m\n'
  for w in "${WARN[@]}"; do printf '    - %s\n' "$w"; done
fi
printf '\n  nvim-viewer を起動して、上部のメニューバーが出れば完了です。\n'
printf '  通常の nvim は今までどおり、この設定の影響を受けません。\n'
printf '  使い方は README.md、キー一覧は起動後に ? を押してください。\n\n'
